import { type CmykObject, type ColorObjType, type HslObject, type HsvObject, type LabObject, type LchObject, type RgbObject, type XyzObject } from '../types';
export declare function toRgbBase(colorObj: ColorObjType): RgbObject;
export declare function rgbNormalizedToRgb(rgb: RgbObject): RgbObject;
export declare function rgbNormalizedToRgbPercent(rgb: RgbObject): RgbObject;
export declare function rgbToNormalizedRgb(rgb: RgbObject): RgbObject;
export declare function rgbToHex(rgb: RgbObject): string | undefined;
export declare function rgbaToHex8(rgba: RgbObject): string;
export declare function rgbNormalizedToHsl(rgb: RgbObject): HslObject;
export declare function rgbNormalizedToHsv(rgb: RgbObject): HsvObject;
export declare function hslToRgbNormalized(hsl: HslObject): RgbObject;
export declare function hsvToRgbNormalized(hsv: HsvObject): RgbObject;
export declare function hexToRgb(hexColor: string): RgbObject;
export declare function xyzToLab(xyz: XyzObject): LabObject;
export declare function labToLch(lab: LabObject): LchObject;
export declare function rgbNormalizedToCmy(rgb: RgbObject): CmykObject;
export declare function cmyToCmyk(cmy: CmykObject): CmykObject;
export declare function lchToLab(lch: LchObject): LabObject;
export declare function labToXyz(lab: LabObject, referenceWhite?: Record<string, number>): XyzObject;
export declare function xyzToRgbNormalized(xyz: XyzObject): RgbObject;
export declare function rgbToXyz(rgb: RgbObject): XyzObject;
//# sourceMappingURL=conversions.d.ts.map